# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('descriptions', models.TextField()),
            ],
        ),
    ]
